"""Add image fields to messages

Revision ID: 7625713143cb
Revises: 7857e637808b
Create Date: 2026-06-29 08:43:33.467511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7625713143cb'
down_revision: Union[str, Sequence[str], None] = '7857e637808b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_type', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_path')
    op.drop_column('messages', 'message_type')
    # ### end Alembic commands ###
